apiVersion: v1
kind: Service
metadata:
  labels:
    app: minecraft-server-odin
  name: minecraft-server-odin
spec:
  ports:
    - name: first
      port: 25565
      protocol: TCP
      targetPort: 25565
    - name: second
      port: 25575
      protocol: TCP
      targetPort: 25575
  selector:
    app: minecraft-server-odin
  type: LoadBalancer
