apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-server
  name: prometheus-deployment
spec:
  ports:
    - name: first
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: prometheus-server
  type: LoadBalancer
