apiVersion: v1
kind: Service
metadata:
  labels:
    app: minecraft-server
  name: minecraft-server
spec:
  ports:
    - name: first
      port: 25565
      protocol: TCP
      targetPort: 25565
    - name: second
      port: 25575
      protocol: TCP
      targetPort: 25575
  selector:
    app: minecraft-server
  type: LoadBalancer
